# Generated by Django 5.2.16 on 2026-08-11 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('supplier', models.CharField(max_length=191)),
                ('order_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='ordered', max_length=32)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('goods_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('payment_status', models.CharField(blank=True, max_length=32)),
                ('shipping_status', models.CharField(blank=True, max_length=32)),
                ('tracking_number', models.CharField(blank=True, max_length=191)),
                ('tracking_url', models.URLField(blank=True, max_length=1000)),
                ('notes', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('part_number', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(blank=True, max_length=150)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('received_quantity', models.PositiveIntegerField(default=0)),
                ('damaged_quantity', models.PositiveIntegerField(default=0)),
                ('wrong_quantity', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('target_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouselocation')),
                ('target_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.legoset')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['owner', 'status', 'deleted_at'], name='orders_orde_owner_i_ef1cd3_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__lte', models.F('quantity'))), name='order_received_lte_quantity'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('damaged_quantity__lte', models.F('quantity'))), name='order_damaged_lte_quantity'),
        ),
    ]
