# Generated by Django 5.2.16 on 2026-08-11 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('collection_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('missing_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('warehouse_quantity', models.PositiveIntegerField(default=0)),
                ('captured_at', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
    ]
