# Generated by Django 5.2.16 on 2026-08-11 22:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_valuesnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceobservation',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
