# Generated by Django 5.2.16 on 2026-08-11 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_workshopdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=191)),
                ('width_mm', models.DecimalField(decimal_places=2, default=50, max_digits=7)),
                ('height_mm', models.DecimalField(decimal_places=2, default=30, max_digits=7)),
                ('orientation', models.CharField(default='landscape', max_length=20)),
                ('configuration', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='unique_owner_label_template')],
            },
        ),
    ]
