# Generated by Django 5.2.16 on 2026-08-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_labeltemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocversion',
            name='name',
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AddField(
            model_name='mocversion',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
