# Generated by Django 5.2.16 on 2026-08-30 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_mocversion_name_mocversion_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='piece_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='status',
            field=models.CharField(choices=[('wish', 'Wunsch'), ('planned', 'Geplant'), ('purchased', 'Gekauft')], default='wish', max_length=20),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='theme',
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
