# Generated by Django 5.2.16 on 2026-09-22 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_portable_active_set_unique'),
        ('organizer', '0005_wishlistitem_image_url_wishlistitem_piece_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setminifigure',
            name='lego_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minifigures_inventory', to='catalog.legoset'),
        ),
    ]
