# Generated by Django 5.2.16 on 2026-08-11 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataQualityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('issue_key', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('severity', models.CharField(default='warning', max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['severity', 'issue_key'],
            },
        ),
        migrations.CreateModel(
            name='RecentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'entity_type', 'entity_id'), name='unique_recent_item')],
            },
        ),
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('area', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=191)),
                ('path', models.CharField(max_length=255)),
                ('configuration', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'area', 'name'), name='unique_saved_view')],
            },
        ),
    ]
