# Generated by Django 5.2.16 on 2026-08-11 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dataqualityissue_recentitem_savedview'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recentitem',
            name='unique_recent_item',
        ),
    ]
