# Generated by Django 5.2.16 on 2026-08-11 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyImportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('source_table', models.CharField(max_length=100)),
                ('source_pk', models.CharField(max_length=100)),
                ('target_model', models.CharField(max_length=150)),
                ('target_pk', models.CharField(max_length=100)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_fingerprint', 'source_table', 'source_pk'), name='unique_legacy_import_record')],
            },
        ),
    ]
