# Generated by Django 5.2.16 on 2026-08-11 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('part_number', models.CharField(max_length=100)),
                ('design_id', models.CharField(blank=True, max_length=100)),
                ('element_id', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(blank=True, max_length=150)),
                ('subcategory', models.CharField(blank=True, max_length=150)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('condition', models.CharField(default='gebraucht', max_length=32)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('source', models.CharField(blank=True, max_length=150)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(max_length=50)),
                ('old_quantity', models.PositiveIntegerField()),
                ('new_quantity', models.PositiveIntegerField()),
                ('difference', models.IntegerField()),
                ('old_reserved', models.PositiveIntegerField(default=0)),
                ('new_reserved', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(blank=True, max_length=191)),
                ('destination', models.CharField(blank=True, max_length=191)),
                ('note', models.TextField(blank=True)),
                ('legacy_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=191)),
                ('location_type', models.CharField(default='Box', max_length=50)),
                ('short_code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('room', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('photo_url', models.URLField(blank=True, max_length=1000)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('locked', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.warehouselocation')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouselocation'),
        ),
        migrations.AddIndex(
            model_name='warehouselocation',
            index=models.Index(fields=['owner', 'active'], name='inventory_w_owner_i_b2d79d_idx'),
        ),
        migrations.AddConstraint(
            model_name='warehouselocation',
            constraint=models.UniqueConstraint(fields=('owner', 'parent', 'name'), name='unique_owner_location'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['owner', 'part_number'], name='inventory_i_owner_i_398037_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['owner', 'element_id'], name='inventory_i_owner_i_6d4515_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('quantity'))), name='inventory_reserved_lte_quantity'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('owner', 'part_number', 'color', 'condition', 'location'), name='unique_inventory_item'),
        ),
    ]
