# Generated by Django 5.2.16 on 2026-08-11 21:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegoSet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legacy_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('set_number', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('theme', models.CharField(blank=True, max_length=150)),
                ('subtheme', models.CharField(blank=True, max_length=150)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_parts', models.PositiveIntegerField(default=0)),
                ('minifigures', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('condition', models.CharField(default='gebraucht', max_length=32)),
                ('completeness', models.CharField(default='unbekannt', max_length=32)),
                ('build_status', models.CharField(default='zerlegt vollständig', max_length=64)),
                ('favorite', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('has_box', models.BooleanField(default=False)),
                ('has_instructions', models.BooleanField(default=False)),
                ('has_stickers', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legacy_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('element_id', models.CharField(max_length=100)),
                ('design_id', models.CharField(blank=True, max_length=100)),
                ('part_number', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=150)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('owned_quantity', models.PositiveIntegerField(default=0)),
                ('unassigned_found_quantity', models.PositiveIntegerField(default=0)),
                ('is_present', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('missing', 'Fehlt'), ('found', 'Gefunden'), ('ordered', 'Bestellt'), ('shipped', 'Versendet'), ('received', 'Erhalten'), ('installed', 'Eingebaut')], default='missing', max_length=16)),
                ('priority', models.CharField(default='normal', max_length=16)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('lego_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='catalog.legoset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'color'],
            },
        ),
        migrations.CreateModel(
            name='PartHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('missing', 'Fehlt'), ('found', 'Gefunden'), ('ordered', 'Bestellt'), ('shipped', 'Versendet'), ('received', 'Erhalten'), ('installed', 'Eingebaut')], max_length=16)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='catalog.part')),
            ],
        ),
        migrations.CreateModel(
            name='SetCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('condition', models.CharField(default='gebraucht', max_length=32)),
                ('completeness', models.CharField(default='unbekannt', max_length=32)),
                ('build_status', models.CharField(default='zerlegt vollständig', max_length=64)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('lego_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='catalog.legoset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SetInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('part_number', models.CharField(max_length=100)),
                ('element_id', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('color_id', models.IntegerField(blank=True, null=True)),
                ('color_name', models.CharField(blank=True, max_length=150)),
                ('required_quantity', models.PositiveIntegerField(default=1)),
                ('owned_quantity', models.PositiveIntegerField(default=0)),
                ('is_spare', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lego_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='catalog.legoset')),
            ],
        ),
        migrations.AddIndex(
            model_name='legoset',
            index=models.Index(fields=['owner', 'set_number'], name='catalog_leg_owner_i_b6825b_idx'),
        ),
        migrations.AddIndex(
            model_name='legoset',
            index=models.Index(fields=['owner', 'year'], name='catalog_leg_owner_i_62ec16_idx'),
        ),
        migrations.AddConstraint(
            model_name='legoset',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('owner', 'set_number'), name='unique_active_set_per_owner'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['owner', 'status', 'deleted_at'], name='catalog_par_owner_i_acd4ee_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['owner', 'element_id'], name='catalog_par_owner_i_88b347_idx'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.CheckConstraint(condition=models.Q(('owned_quantity__lte', models.F('quantity'))), name='part_owned_lte_quantity'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='part_quantity_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='setinventoryitem',
            index=models.Index(fields=['lego_set', 'part_number'], name='catalog_set_lego_se_2bdccf_idx'),
        ),
        migrations.AddIndex(
            model_name='setinventoryitem',
            index=models.Index(fields=['element_id'], name='catalog_set_element_cdb9eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='setinventoryitem',
            constraint=models.UniqueConstraint(fields=('lego_set', 'part_number', 'color_id', 'is_spare'), name='unique_set_inventory_item'),
        ),
        migrations.AddConstraint(
            model_name='setinventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('owned_quantity__gte', 0)), name='set_inventory_owned_nonnegative'),
        ),
    ]
