# Generated by Django 5.2.16 on 2026-08-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setcopy',
            name='legacy_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
