# Generated by Django 5.2.16 on 2026-08-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_setcopy_legacy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='parthistory',
            name='legacy_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
